apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-driver
  namespace: jupyterlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rb
  namespace: jupyterlab
subjects:
  - kind: ServiceAccount
    name: spark-driver
    namespace: jupyterlab
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

