apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyterlab
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
  - name: http
    port: 8888
    protocol: TCP
    nodePort: 30002
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-headless
  namespace: jupyterlab
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    release: jupyter
  ports:
  - name: http
    port: 8888
    protocol: TCP
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP