apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  destination:
    namespace: superset
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
  sources:
    - repoURL: https://github.com/stephen-do/big_data_storage_integration_processing.git
      targetRevision: main
      ref: apps
    - repoURL: http://apache.github.io/superset/
      targetRevision: 0.12.0
      chart: superset
      helm:
        valueFiles:
          - $apps/apps/superset/values.yaml