apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GIT_SYNC_USERNAME: c3RlcGhlbi1kbw==
  GIT_SYNC_PASSWORD: Z2hwX2JKTWd0OUJiN2Q4YmJvNkdFa2VvS2pkbU43Z0g3NDFwRjNUVA==
  GITSYNC_USERNAME: c3RlcGhlbi1kbw==
  GITSYNC_PASSWORD: Z2hwX2JKTWd0OUJiN2Q4YmJvNkdFa2VvS2pkbU43Z0g3NDFwRjNUVA==