apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GIT_SYNC_USERNAME: bmd1eWVubmh1bmFp
  GIT_SYNC_PASSWORD: Z2hwX3h6UGlyREdwMDVzWGFQMXlnQU02SVZjQ0ZhbjlTVjJSWDUxWA==
  GITSYNC_USERNAME: bmd1eWVubmh1bmFp
  GITSYNC_PASSWORD: Z2hwX3h6UGlyREdwMDVzWGFQMXlnQU02SVZjQ0ZhbjlTVjJSWDUxWA==