apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  destination:
    namespace: spark
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
  sources:
    - repoURL: https://github.com/stephen-do/big_data_storage_integration_processing.git
      targetRevision: main
      ref: apps
    - repoURL: https://kubeflow.github.io/spark-operator
      targetRevision: 2.1.1
      chart: spark-operator