apiVersion: v1
kind: Pod
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    app: jupyterlab
spec:
  serviceAccountName: spark-driver
  securityContext:
    fsGroup: 777
  containers:
  - name: jupyter-driver-pod
    image: dongoctuyen/jupyterlab:spark-base-v3.4
    imagePullPolicy: IfNotPresent
    command: ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    volumeMounts:
    - name: notebook-data
      mountPath: /root/.jupyter/jupyter_notebook_config.py
      subPath: app_configuration.py
  volumes:
  - name: notebook-data
    configMap:
      name: jupyter-notebook-config
  restartPolicy: Always
