apiVersion: v1
kind: Pod
metadata:
  name: jupyterlab
  namespace: jupyterlab
  labels:
    app: jupyterlab
spec:
  serviceAccountName: spark-driver
  securityContext:
    fsGroup: 777
  containers:
  - name: jupyter-driver-pod
    image: dongoctuyen/jupyterlab:spark-base-v3.4
    imagePullPolicy: IfNotPresent
    command: ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    volumeMounts:
    - name: notebook-data
      mountPath: /opt/spark/work-dir/
  volumes:
    - name: notebook-data
      persistentVolumeClaim:
        claimName: jupyterlab
  restartPolicy: Always
