apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio-dev
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
  sources:
    - repoURL: https://github.com/stephen-do/big_data_storage_integration_processing.git
      targetRevision: main
      ref: apps
      path: apps/minio
      directory:
        recurse: true